### ISSUE TITLE
stata command rdrobust option covs() error

### ISSUE THREAD

**Issue by xzhang044** [rdpackages-replication/C_2020_Chamberlain#1]
When I run the code :

rdrobust $y $x, covs($covs) 

It shows "option covs() not allowed" 

Is it a version issue? In the latest version of rdrobust, there is no covs() option. 

How to run the regression with covariates in the new version? 

Thanks.

**Comment by mdcattaneo** [comment]
The option is available. Please make sure to run the replication file as given to verify it.
